import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex items-center justify-center min-h-[100vh]">
          <h1 className=" text-sky-400 font-bold text-4xl">Hi Developers</h1>
        </div>
      </main>
    </div>
  );
}
